lib/ratethedub_web/router.ex
defmodule RateTheDubWeb.Router do
  use RateTheDubWeb, :router

  pipeline :browser do
    plug RemoteIp,
      headers: ["fly-client-ip"]

    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

    plug SetLocale,
      gettext: RateTheDubWeb.Gettext,
      default_locale: "en"

    # plug RateTheDubWeb.GoatcounterPlug
  end

  pipeline :api do
    plug RemoteIp,
      headers: ["fly-client-ip"]

    plug :accepts, ["json", "application/vnd.api+json"]

    # plug RateTheDubWeb.GoatcounterPlug
  end

  pipeline :sitemap do
    plug RemoteIp,
      headers: ["fly-client-ip"]

    plug :accepts, ["xml"]

    # plug RateTheDubWeb.GoatcounterPlug
  end

  # Due to conflicts with the locale redirection system this must come before
  # the browser scopes
  scope "/api", RateTheDubWeb do
    pipe_through :api

    get "/", APIController, :index
    get "/featured", APIController, :featured
    get "/trending", APIController, :trending
    get "/top", APIController, :top
    get "/anime/:id", APIController, :series
  end

  scope "/sitemap.xml", RateTheDubWeb do
    pipe_through :sitemap

    get "/", PageController, :sitemap
  end

  # Required to ensure that the blank paths without locales still function and
  # redirect properly. Should mirror the scope below it.
  # Should never be called and logs an error if it does
  scope "/", RateTheDubWeb do
    pipe_through :browser

    get "/", PageController, :dummy
    get "/about", PageController, :dummy

    get "/anime/:id", PageController, :dummy
    post "/anime/:id", PageController, :dummy
    delete "/anime/:id", PageController, :dummy

    get "/search", PageController, :dummy
  end

  scope "/:locale", RateTheDubWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/about", PageController, :about

    get "/anime/:id", AnimeController, :show
    post "/anime/:id", AnimeController, :vote
    delete "/anime/:id", AnimeController, :undo

    get "/search", SearchController, :index
  end
end

lib/ratethedub_web/templates/page/about.html.eex
<article>
  <h1 class="text-4xl"><%= gettext "About" %></h1>
  <p>
    RateTheDub is a site where you can view and vote on whether or not the dub for
    various anime series was any good. The goal is to eliminate the random searching
    and digging through old forum posts that is currently required to figure out if
    a dub is any good.
  </p>
  <p>
    It was born out of the author's own frustration with needing to browse
    random old forum posts just to figure out if the dub for an anime was any
    good.
  </p>

  <p>
    <blockquote class="italic text-opacity-50">"But subs are better than dubs!"</blockquote>
    you might say, and is the usual argument against dubs and anything related
    to them.
    Well not everyone can read subs, the visually impaired or children. And in
    some languages the dubs actually are better (or more well liked) than the
    subtitles.
  </p>

  <p>
    This project is open source and written in Elixir.
    <a href="https://github.com/rushsteve1/RateTheDub">Come help us out on GitHub!</a>
  </p>

  <h2 class="text-3xl" id="contact"><%= gettext "Contact" %></h2>
  <p>
    You can send us an email at <a href="mailto:contact@ratethedub.com">contact@ratethedub.com</a>
  </p>

  <h2 class="text-3xl" id="feedback"><%= gettext "Feedback" %></h2>
  <p>
    We're working on a system for feedback/comments on individual series. For
    now all general feedback should be directed to the email address above.
  </p>

  <h3 class="text-2xl"><%= gettext "Database Changes" %></h3>
  <p>
    We're working on a system where you can point out issues and request changes
    with out date (missing languages, wrong title, etc.) so we'll update this
    section soon!
  </p>

  <h2 class="text-3xl" id="donate"><%= gettext "Donate" %></h2>
  <p>
    Holding off on this until we're at least out of Beta and have something that
    we'd feel proud of enough.
  </p>
</article>

lib/ratethedub_web/templates/page/index.html.eex
<div id="jumbo" class="text-4xl font-semibold text-center mb-8">
  <%= gettext "Is the" %>
  <span class="text-dark-olive">
    <%= RateTheDub.Locale.locale_own_name @locale %>
  </span>
  <%= gettext "dub for" %>
  <span class="text-mandarin"><%= gettext "that anime" %></span>
  <%= gettext "any good?" %>
</div>

<section class="grid grid-cols-1 md:grid-cols-3 grid-rows-1 gap-10">
  <section>
    <h2 class="text-center text-xl"><%= gettext "Featured" %></h2>
    <%= render RateTheDubWeb.PageView, "series-list.html", conn: @conn, locale: @locale, series: @featured %>
  </section>

  <section>
    <h2 class="text-center text-xl"><%= gettext "Trending" %></h2>
    <%= render RateTheDubWeb.PageView, "series-list.html", conn: @conn, locale: @locale, series: @trending %>
  </section>

  <section>
    <h2 class="text-center text-xl"><%= gettext "Top Rated" %></h2>
    <%= render RateTheDubWeb.PageView, "series-list.html", conn: @conn, locale: @locale, series: @top_rated %>
  </section>
</section>

lib/ratethedub_web/templates/page/series-list.html.eex
<ul>
  <%= for [anime, count] <- @series do %>
    <li>
      <a
        href="<%= Routes.anime_path(@conn, :show, @locale, anime.mal_id) %>"
        class="flex align-center justify-center h-20 my-4 border-2 border-independence cursor-pointer transition-shadow hover:shadow w-full"
      >
          <img
            src="<%= anime.poster_url %>"
            title="<%= anime.title %>"
            class="inline-block max-h-full"
          />
          <span class="flex-grow px-2 truncate"><%= anime.title %></span>
          <%= if count > 0 do %>
          <div
            class="px-3 bg-independence text-white font-bold h-full flex flex-col justify-center align-center"
          >
            <span><%= count %></span>
          </div>
          <% end %>
      </a>
    </li>
  <% end %>
</ul>

lib/ratethedub_web/templates/page/sitemap.xml.eex
<?xml version="1.0" encoding="UTF-8"?>

<urlset
      xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
            http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">

  <url>
    <loc>https://ratethedub.com/</loc>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>

  <url>
    <loc>https://ratethedub.com/about</loc>
    <changefreq>monthly</changefreq>
    <priority>0.3</priority>
  </url>

  <%= for series <- @series do %>
    <%= for locale <- series.dubbed_in do %>
    <url>
      <loc><%= "https://ratethedub.com/#{locale}/#{series.mal_id}" %></loc>
      <changefreq>hourly</changefreq>
      <priority>0.5</priority>
    </url>
    <% end %>
  <% end %>

</urlset>